apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xfl145nqc-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:2863b7e14c2cb56de28607ad946a8f5d8f9d8271@sha256:9aecd8ba4a82c35a3d169598d320f2e3d86876a9459d663a6b6e28302ce0fe94
          name: container-image
