apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xfl145nqc-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xfl145nqc-dotnet-basic-gitops